// packages/react/src/mcp/mcp-tool-form.tsx
import { useState } from 'react'
import { cn, schemaToFields } from '@mcp-elements/core'
import type { JsonSchema, FieldDescriptor } from '@mcp-elements/core'

export interface McpToolFormProps {
  schema: JsonSchema
  onSubmit: (args: Record<string, unknown>) => void
  loading?: boolean
  submitLabel?: string
  className?: string
}

function FieldInput({
  field,
  value,
  onChange,
}: {
  field: FieldDescriptor
  value: unknown
  onChange: (v: unknown) => void
}) {
  const str = typeof value === 'string' ? value : value == null ? '' : String(value)

  switch (field.kind) {
    case 'switch':
      return (
        <input
          type="checkbox"
          id={field.key}
          checked={Boolean(value)}
          onChange={(e) => onChange(e.target.checked)}
          className="mcpe-switch"
          aria-label={field.label}
        />
      )

    case 'select':
      return (
        <select
          id={field.key}
          value={str}
          onChange={(e) => onChange(e.target.value)}
          className="mcpe-select"
          required={field.required}
        >
          <option value="">Select…</option>
          {field.options?.map((opt) => (
            <option key={opt.value} value={opt.value}>{opt.label}</option>
          ))}
        </select>
      )

    case 'multiselect':
      return (
        <select
          id={field.key}
          multiple
          value={Array.isArray(value) ? value.map(String) : []}
          onChange={(e) => {
            const selected = Array.from(e.target.selectedOptions).map((o) => o.value)
            onChange(selected)
          }}
          className="mcpe-select"
          required={field.required}
        >
          {field.options?.map((opt) => (
            <option key={opt.value} value={opt.value}>{opt.label}</option>
          ))}
        </select>
      )

    case 'textarea':
      return (
        <textarea
          id={field.key}
          value={str}
          onChange={(e) => onChange(e.target.value)}
          className="mcpe-textarea"
          required={field.required}
          minLength={field.minLength}
          maxLength={field.maxLength}
          rows={4}
        />
      )

    case 'number':
      return (
        <input
          type="number"
          id={field.key}
          value={str}
          onChange={(e) => onChange(e.target.valueAsNumber)}
          className="mcpe-input"
          required={field.required}
          min={field.min}
          max={field.max}
        />
      )

    case 'unknown':
      return (
        <input
          type="text"
          id={field.key}
          value={str}
          onChange={(e) => onChange(e.target.value)}
          className="mcpe-input"
          disabled
          placeholder="(unsupported field type)"
        />
      )

    default:
      return (
        <input
          type={field.kind === 'email' ? 'email' : field.kind === 'url' ? 'url' : field.kind === 'date' ? 'date' : 'text'}
          id={field.key}
          value={str}
          onChange={(e) => onChange(e.target.value)}
          className="mcpe-input"
          required={field.required}
          pattern={field.pattern}
          minLength={field.minLength}
          maxLength={field.maxLength}
        />
      )
  }
}

export function McpToolForm({
  schema,
  onSubmit,
  loading = false,
  submitLabel = 'Run',
  className,
}: McpToolFormProps) {
  const fields = schemaToFields(schema)
  const [values, setValues] = useState<Record<string, unknown>>(() => {
    const defaults: Record<string, unknown> = {}
    for (const f of fields) {
      if (f.defaultValue !== undefined) defaults[f.key] = f.defaultValue
    }
    return defaults
  })

  function setValue(key: string, value: unknown) {
    setValues((prev) => ({ ...prev, [key]: value }))
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    onSubmit(values)
  }

  if (fields.length === 0) {
    return (
      <form onSubmit={handleSubmit} className={cn('mcpe-mcp-tool-form', className)}>
        <p className="text-sm text-muted-foreground">This tool takes no inputs.</p>
        <div className="mcpe-mcp-tool-form-submit">
          <button type="submit" className="mcpe-btn mcpe-btn-primary mcpe-btn-sm" disabled={loading}>
            {loading ? 'Running…' : submitLabel}
          </button>
        </div>
      </form>
    )
  }

  return (
    <form onSubmit={handleSubmit} className={cn('mcpe-mcp-tool-form', className)}>
      {fields.map((field) => (
        <div key={field.key} className="mcpe-mcp-tool-form-field">
          <label
            htmlFor={field.key}
            className={cn('mcpe-mcp-tool-form-label', field.required && 'mcpe-mcp-tool-form-label-required')}
          >
            {field.label}
          </label>
          <FieldInput field={field} value={values[field.key]} onChange={(v) => setValue(field.key, v)} />
          {field.help && <p className="mcpe-mcp-tool-form-help">{field.help}</p>}
        </div>
      ))}
      <div className="mcpe-mcp-tool-form-submit">
        <button type="submit" className="mcpe-btn mcpe-btn-primary mcpe-btn-sm" disabled={loading}>
          {loading ? 'Running…' : submitLabel}
        </button>
      </div>
    </form>
  )
}

// packages/angular/src/mcp/mcp-tool-form.component.ts
import { Component, input, output, signal, computed, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn, schemaToFields } from '@mcp-elements/core'
import type { JsonSchema, FieldDescriptor } from '@mcp-elements/core'

@Component({
  selector: 'mcpe-mcp-tool-form',
  standalone: true,
  imports: [CommonModule],
  template: `
    <form [class]="classes()" (ngSubmit)="handleSubmit()">
      @if (fields().length === 0) {
        <p class="text-sm text-muted-foreground">This tool takes no inputs.</p>
      }
      @for (field of fields(); track field.key) {
        <div class="mcpe-mcp-tool-form-field">
          <label
            [for]="field.key"
            [class]="labelClass(field)"
          >{{ field.label }}</label>
          @switch (field.kind) {
            @case ('switch') {
              <input type="checkbox" [id]="field.key" class="mcpe-switch"
                [checked]="getBool(field.key)"
                (change)="setValue(field.key, $any($event.target).checked)" />
            }
            @case ('select') {
              <select [id]="field.key" class="mcpe-select"
                [value]="getStr(field.key)"
                (change)="setValue(field.key, $any($event.target).value)">
                <option value="">Select…</option>
                @for (opt of field.options ?? []; track opt.value) {
                  <option [value]="opt.value">{{ opt.label }}</option>
                }
              </select>
            }
            @case ('textarea') {
              <textarea [id]="field.key" class="mcpe-textarea" rows="4"
                [value]="getStr(field.key)"
                (input)="setValue(field.key, $any($event.target).value)"></textarea>
            }
            @case ('number') {
              <input type="number" [id]="field.key" class="mcpe-input"
                [value]="getStr(field.key)"
                (input)="setValue(field.key, +$any($event.target).value)" />
            }
            @default {
              <input [type]="inputType(field)" [id]="field.key" class="mcpe-input"
                [value]="getStr(field.key)"
                (input)="setValue(field.key, $any($event.target).value)" />
            }
          }
          @if (field.help) {
            <p class="mcpe-mcp-tool-form-help">{{ field.help }}</p>
          }
        </div>
      }
      <div class="mcpe-mcp-tool-form-submit">
        <button type="submit" class="mcpe-btn mcpe-btn-primary mcpe-btn-sm" [disabled]="loading()">
          {{ loading() ? 'Running…' : submitLabel() }}
        </button>
      </div>
    </form>
  `,
})
export class McpeMcpToolFormComponent implements OnInit {
  schema = input.required<JsonSchema>()
  loading = input(false)
  submitLabel = input('Run')
  class = input('')
  onSubmit = output<Record<string, unknown>>()

  fields = computed(() => schemaToFields(this.schema()))
  values = signal<Record<string, unknown>>({})

  ngOnInit() {
    const defaults: Record<string, unknown> = {}
    for (const f of this.fields()) {
      if (f.defaultValue !== undefined) defaults[f.key] = f.defaultValue
    }
    this.values.set(defaults)
  }

  classes = computed(() => cn('mcpe-mcp-tool-form', this.class()))

  setValue(key: string, value: unknown) {
    this.values.update((v: Record<string, unknown>) => ({ ...v, [key]: value }))
  }

  getStr(key: string): string {
    const v = this.values()[key]
    return v == null ? '' : String(v)
  }

  getBool(key: string): boolean {
    return Boolean(this.values()[key])
  }

  labelClass(field: FieldDescriptor): string {
    return cn('mcpe-mcp-tool-form-label', field.required ? 'mcpe-mcp-tool-form-label-required' : '')
  }

  inputType(field: FieldDescriptor): string {
    switch (field.kind) {
      case 'email': return 'email'
      case 'url': return 'url'
      case 'date': return 'date'
      default: return 'text'
    }
  }

  handleSubmit() {
    this.onSubmit.emit(this.values())
  }
}
