// packages/react/src/avatar.tsx
import { forwardRef, useState } from 'react'
import { cn } from '@mcp-elements/core'

export interface AvatarProps extends React.HTMLAttributes<HTMLDivElement> {
  src?: string
  alt?: string
  fallback?: string
}

export const Avatar = forwardRef<HTMLDivElement, AvatarProps>(
  ({ src, alt, fallback, className, ...props }, ref) => {
    const [hasError, setHasError] = useState(false)

    return (
      <div ref={ref} className={cn('mcpe-avatar', className)} {...props}>
        {src && !hasError ? (
          <img src={src} alt={alt} className="mcpe-avatar-image" onError={() => setHasError(true)} />
        ) : (
          <span className="mcpe-avatar-fallback">{fallback}</span>
        )}
      </div>
    )
  }
)
Avatar.displayName = 'Avatar'

// packages/angular/src/avatar.component.ts
import { Component, input, computed, signal } from '@angular/core'

@Component({
  selector: 'mcpe-avatar',
  standalone: true,
  template: `
    <div [class]="classes()">
      @if (src() && !hasError()) {
        <img [src]="src()" [alt]="alt()" class="mcpe-avatar-image" (error)="hasError.set(true)" />
      } @else {
        <span class="mcpe-avatar-fallback">{{ fallback() }}</span>
      }
    </div>
  `,
})
export class SnxAvatarComponent {
  src = input<string>('')
  alt = input('')
  fallback = input('')
  class = input('')
  hasError = signal(false)

  classes = computed(() => ['mcpe-avatar', this.class()].filter(Boolean).join(' '))
}
