// packages/angular/src/badge.component.ts
import { Component, computed, input } from '@angular/core'

type BadgeVariant = 'default' | 'secondary' | 'outline' | 'destructive'

@Component({
  selector: 'mcpe-badge',
  standalone: true,
  template: `<span [class]="classes()"><ng-content /></span>`,
})
export class SnxBadgeComponent {
  variant = input<BadgeVariant>('default')
  class = input('')

  classes = computed(() =>
    ['mcpe-badge', `mcpe-badge-${this.variant()}`, this.class()].filter(Boolean).join(' ')
  )
}

// packages/react/src/badge.tsx
import { cn } from '@mcp-elements/core'

export interface BadgeProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'default' | 'secondary' | 'outline' | 'destructive'
}

export function Badge({ variant = 'default', className, ...props }: BadgeProps) {
  return <div className={cn('mcpe-badge', `mcpe-badge-${variant}`, className)} {...props} />
}
