// packages/angular/src/dialog.component.ts
import { Component, input, output, signal, effect, ElementRef, viewChild } from '@angular/core'
import { trapFocus, lockScroll } from '@mcp-elements/core'

@Component({
  selector: 'mcpe-dialog',
  standalone: true,
  host: { '(document:keydown)': 'onKeydown($event)' },
  template: `
    @if (open()) {
      <div class="mcpe-dialog-overlay" (click)="close()">
        <div
          #content
          class="mcpe-dialog-content"
          role="dialog"
          tabindex="-1"
          [attr.aria-modal]="modal()"
          (click)="$event.stopPropagation()"
        >
          <ng-content />
          <button class="mcpe-dialog-close" (click)="close()" type="button" aria-label="Close">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="M18 6 6 18" /><path d="m6 6 12 12" />
            </svg>
          </button>
        </div>
      </div>
    }
  `,
})
export class SnxDialogComponent {
  modal = input(true)
  open = signal(false)
  openChange = output<boolean>()

  content = viewChild<ElementRef<HTMLElement>>('content')
  private previouslyFocused: HTMLElement | null = null
  private unlockScroll: (() => void) | null = null

  constructor() {
    effect(() => {
      if (this.open()) {
        this.previouslyFocused = document.activeElement as HTMLElement | null
        if (this.modal()) this.unlockScroll = lockScroll()
        // Focus the dialog once the view has rendered it.
        setTimeout(() => this.content()?.nativeElement.focus())
      } else {
        this.unlockScroll?.()
        this.unlockScroll = null
        this.previouslyFocused?.focus?.()
        this.previouslyFocused = null
      }
    })
  }

  onKeydown(e: KeyboardEvent) {
    if (!this.open()) return
    if (e.key === 'Escape') {
      this.close()
      return
    }
    if (e.key === 'Tab') {
      const el = this.content()?.nativeElement
      if (el) trapFocus(el, e)
    }
  }

  toggle() {
    this.open.update(v => !v)
    this.openChange.emit(this.open())
  }

  close() {
    this.open.set(false)
    this.openChange.emit(false)
  }

  show() {
    this.open.set(true)
    this.openChange.emit(true)
  }
}

// packages/react/src/dialog.tsx
import { useEffect, useRef, useId, createContext, useContext } from 'react'
import { createPortal } from 'react-dom'
import { cn, trapFocus, lockScroll } from '@mcp-elements/core'
import { useDialog } from './hooks/use-dialog'

const DialogIdContext = createContext<string>('')

export interface DialogProps {
  open?: boolean
  onOpenChange?: (open: boolean) => void
  modal?: boolean
  children: React.ReactNode
}

export function Dialog({ open: controlledOpen, onOpenChange, modal = true, children }: DialogProps) {
  const dialog = useDialog({ modal })
  const isOpen = controlledOpen ?? dialog.open
  const setOpen = onOpenChange ?? dialog.setOpen
  const contentRef = useRef<HTMLDivElement>(null)
  const dialogId = useId()

  useEffect(() => {
    if (!isOpen || !modal) return
    const unlock = lockScroll()
    return unlock
  }, [isOpen, modal])

  useEffect(() => {
    if (!isOpen || !contentRef.current) return
    const el = contentRef.current
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setOpen(false)
        return
      }
      trapFocus(el, e)
    }
    el.addEventListener('keydown', handler)
    return () => el.removeEventListener('keydown', handler)
  }, [isOpen])

  if (!isOpen || typeof document === 'undefined') return null

  return createPortal(
    <DialogIdContext.Provider value={dialogId}>
      <div className="mcpe-dialog-overlay" onClick={() => setOpen(false)}>
        <div
          ref={contentRef}
          className="mcpe-dialog-content"
          role="dialog"
          aria-modal={modal}
          aria-labelledby={`${dialogId}-title`}
          aria-describedby={`${dialogId}-description`}
          onClick={(e) => e.stopPropagation()}
        >
          {children}
          <button
            className="mcpe-dialog-close"
            aria-label="Close"
            onClick={() => setOpen(false)}
            type="button"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <path d="M18 6 6 18" /><path d="m6 6 12 12" />
            </svg>
          </button>
        </div>
      </div>
    </DialogIdContext.Provider>,
    document.body
  )
}

export function DialogHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('mcpe-dialog-header', className)} {...props} />
}

export function DialogFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('mcpe-dialog-footer', className)} {...props} />
}

export function DialogTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) {
  const dialogId = useContext(DialogIdContext)
  return <h2 id={`${dialogId}-title`} className={cn('mcpe-dialog-title', className)} {...props} />
}

export function DialogDescription({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) {
  const dialogId = useContext(DialogIdContext)
  return <p id={`${dialogId}-description`} className={cn('mcpe-dialog-description', className)} {...props} />
}

export { useDialog } from './hooks/use-dialog'
