// packages/angular/src/loader.component.ts
import { Component, input, computed } from '@angular/core'

@Component({
  selector: 'mcpe-loader',
  standalone: true,
  template: `<div [class]="classes()" role="status" aria-label="Loading"><span class="sr-only">Loading...</span></div>`,
})
export class SnxLoaderComponent {
  size = input<'sm' | 'md' | 'lg' | 'xl'>('md')
  variant = input<'primary' | 'muted'>('primary')
  classes = computed(() => `mcpe-loader mcpe-loader-${this.size()} mcpe-loader-${this.variant()}`)
}

// packages/react/src/loader.tsx
import { cn } from '@mcp-elements/core'

export interface LoaderProps extends React.HTMLAttributes<HTMLDivElement> {
  size?: 'sm' | 'md' | 'lg' | 'xl'
  variant?: 'primary' | 'muted'
}

export function Loader({ size = 'md', variant = 'primary', className, ...props }: LoaderProps) {
  return (
    <div
      role="status"
      aria-label="Loading"
      className={cn('mcpe-loader', `mcpe-loader-${size}`, `mcpe-loader-${variant}`, className)}
      {...props}
    >
      <span className="sr-only">Loading...</span>
    </div>
  )
}
