// packages/angular/src/mcp/mcp-server-status.component.ts
import { Component, input, computed } from '@angular/core'
import { cn } from '@mcp-elements/core'

export type McpConnectionStatus = 'connected' | 'connecting' | 'disconnected' | 'error'

const STATUS_LABELS: Record<McpConnectionStatus, string> = {
  connected: 'Connected',
  connecting: 'Connecting',
  disconnected: 'Disconnected',
  error: 'Error',
}

@Component({
  selector: 'mcpe-mcp-server-status',
  standalone: true,
  template: `
    <span
      [class]="classes()"
      role="status"
      aria-live="polite"
      [attr.aria-label]="ariaLabel()"
    >
      <span class="mcpe-mcp-server-status-dot" aria-hidden="true"></span>
      {{ label() }}
    </span>
  `,
})
export class McpeMcpServerStatusComponent {
  status = input.required<McpConnectionStatus>()
  serverName = input<string>()
  class = input('')

  classes = computed(() => cn('mcpe-mcp-server-status', `mcpe-mcp-server-status-${this.status()}`, this.class()))
  label = computed(() => {
    const s = this.serverName()
    const statusLabel = STATUS_LABELS[this.status() as McpConnectionStatus]
    return s ? `${s} · ${statusLabel}` : statusLabel
  })
  ariaLabel = computed(() => {
    const s = this.serverName()
    const statusLabel = STATUS_LABELS[this.status() as McpConnectionStatus]
    return s ? `${s}: ${statusLabel}` : statusLabel
  })
}

// packages/react/src/mcp/mcp-server-status.tsx
import type React from 'react'
import { cn } from '@mcp-elements/core'

export type McpConnectionStatus = 'connected' | 'connecting' | 'disconnected' | 'error'

export interface McpServerStatusProps extends React.HTMLAttributes<HTMLSpanElement> {
  status: McpConnectionStatus
  serverName?: string
}

const STATUS_LABELS: Record<McpConnectionStatus, string> = {
  connected: 'Connected',
  connecting: 'Connecting',
  disconnected: 'Disconnected',
  error: 'Error',
}

export function McpServerStatus({ status, serverName, className, ...props }: McpServerStatusProps) {
  return (
    <span
      role="status"
      aria-live="polite"
      aria-label={serverName ? `${serverName}: ${STATUS_LABELS[status]}` : STATUS_LABELS[status]}
      {...props}
      className={cn(
        'mcpe-mcp-server-status',
        `mcpe-mcp-server-status-${status}`,
        className,
      )}
    >
      <span className="mcpe-mcp-server-status-dot" aria-hidden="true" />
      {serverName ? `${serverName} · ${STATUS_LABELS[status]}` : STATUS_LABELS[status]}
    </span>
  )
}
